displayName=HDR
author=Endrit
description=Adjusts OSRS terrain tile lighting, shadows, and saturation with area-specific HDR profiles.
tags=hdr,lighting,lightness,brightness,shadow,saturation,tiles,terrain,raids,cox,toa,tob,poh,dungeon,doom,mokhaiotl
plugins=com.endrit.hdr.HDRPlugin
build=standard
version=1.0
